# -*- coding: utf-8 -*-
"""desinformacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9soxo7nQfI-SKZcUKhXwyHnGWxSVPnu
"""

# 1. Instala las librerías necesarias en Colab (si no las tienes)
!pip install pytrends pandas matplotlib seaborn

from pytrends.request import TrendReq
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Configurar estilo visual para que se vea profesional en una presentación
sns.set_theme(style="whitegrid")
plt.rcParams['font.family'] = 'sans-serif'

# 3. Inicializar la conexión con Google Trends
print("Conectando a Google Trends...")
pytrends = TrendReq(hl='en-US', tz=360)

# 4. Definir las búsquedas de desinformación
# Usamos términos comunes del "Nuevo Negacionismo"
keywords = ["climate hoax", "climate scam"]

try:
    # 5. Extraer datos globales de los últimos 5 años
    pytrends.build_payload(kw_list=keywords, cat=0, timeframe='today 5-y', geo='')
    df = pytrends.interest_over_time()

    if not df.empty:
        # Limpiar datos de Google
        df = df.drop(columns=['isPartial'])

        # Agrupar por mes para que la línea no se vea ruidosa y muestre la tendencia clara
        df_monthly = df.resample('ME').mean()

        # 6. Crear el Gráfico
        fig, ax = plt.subplots(figsize=(10, 5), dpi=150)

        # Colores de advertencia (Rojo y Naranja)
        colors = ['#d62728', '#ff7f0e']

        for i, kw in enumerate(keywords):
            ax.plot(df_monthly.index, df_monthly[kw], label=kw.title(), linewidth=2.5, color=colors[i])

        # Títulos y Etiquetas
        plt.title('Aumento de Búsquedas de Desinformación Climática (Últimos 5 Años)',
                  fontsize=16, fontweight='bold', pad=20)
        plt.xlabel('Año', fontsize=12)
        plt.ylabel('Volumen de Búsqueda Relativo', fontsize=12)

        # Leyenda
        plt.legend(title="Términos (Inglés)", fontsize=11, title_fontsize=12, loc='upper left')

        # Eliminar bordes innecesarios para un look más "startup"
        sns.despine(left=True, bottom=True)

        # Ajustar y mostrar
        plt.tight_layout()

        # Guardamos la imagen para que la puedas poner en tu pitch deck
        plt.savefig('grafico_desinformacion_pitch.png', bbox_inches='tight')
        print("¡Éxito! Gráfico guardado como 'grafico_desinformacion_pitch.png'")

        # Mostrar en pantalla
        plt.show()

    else:
        print("No se encontraron datos. Intenta con otros términos.")

except Exception as e:
    print(f"Error: {e}")

from pytrends.request import TrendReq
import pandas as pd

# Inicializar
pytrends = TrendReq(hl='en-US', tz=360)

# Buscamos qué más busca la gente cuando busca "climate hoax" (engaño climático)
keyword = "climate hoax"
print(f"Buscando consultas relacionadas para: '{keyword}'...")

try:
    pytrends.build_payload(kw_list=[keyword], timeframe='today 12-m')
    related = pytrends.related_queries()

    # Extraer las búsquedas que más han crecido recientemente
    rising_queries = related[keyword]['rising']

    if rising_queries is not None:
        print("\n🔥 BÚSQUEDAS EN AUMENTO (Ideal para mostrar en tu Pitch):")
        print(rising_queries.head(10))
    else:
        print("No hay suficientes datos de búsquedas en aumento para esta palabra hoy.")

except Exception as e:
    print(f"Error: {e}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Creamos un dataset simulado de titulares extraídos (Como si hubieras hecho scraping)
data = {
    "titular": [
        "Los glaciares suizos en realidad están creciendo este invierno",
        "El calentamiento global es solo el ciclo solar natural",
        "Los paneles solares contaminan más que el carbón",
        "Siempre ha hecho calor en verano, no es para tanto",
        "Coches eléctricos son una estafa de la élite",
        "El retroceso de los glaciares es normal desde la edad de hielo",
        "La capa de nieve en los Alpes está perfecta este año"
    ]
}
df = pd.DataFrame(data)

# 2. Lógica de clasificación basada en tu PDF (El "Nuevo Negacionismo")
def clasificar_desinformacion(texto):
    texto = texto.lower()
    if any(word in texto for word in ['ciclo solar', 'natural', 'edad de hielo', 'siempre ha hecho']):
        return "Causas Naturales (Minimización)"
    elif any(word in texto for word in ['paneles', 'eléctricos', 'estafa', 'contaminan']):
        return "Ataque a Soluciones (Retardismo)"
    elif any(word in texto for word in ['creciendo', 'perfecta', 'nieve']):
        return "Negación Directa (Fácil de desmentir con Satélite)"
    else:
        return "Otro"

# Aplicamos la clasificación
df['categoria'] = df['titular'].apply(clasificar_desinformacion)

# 3. Generar el gráfico para la Hackathon
plt.figure(figsize=(8, 5))
colores = ['#ff9999','#66b3ff','#99ff99']
df['categoria'].value_counts().plot(kind='pie', autopct='%1.1f%%', colors=colores, startangle=90, wedgeprops={'edgecolor': 'black'})

plt.title('Clasificación de Narrativas del "Nuevo Negacionismo"', fontweight='bold')
plt.ylabel('') # Quitar etiqueta del eje Y para que se vea limpio
plt.tight_layout()

# Guardar y mostrar
plt.savefig('categorias_desinformacion.png', dpi=150)
print("¡Gráfico de categorías guardado como 'categorias_desinformacion.png'!")
plt.show()

from pytrends.request import TrendReq
import time

# 1. Inicializar
pytrends = TrendReq(hl='en-US', tz=360)

# 2. ¡MÁS KEYWORDS! Agregamos varias narrativas falsas comunes
keywords = ["climate hoax", "climate scam", "global warming fake", "glaciers growing"]

print("🔍 RASTREADOR DE NARRATIVAS FALSAS (IBILENS)\n" + "-"*40)

for kw in keywords:
    try:
        # Pytrends solo permite 5 a la vez, por eso usamos un loop (1 por 1)
        pytrends.build_payload(kw_list=[kw], timeframe='today 12-m')
        related = pytrends.related_queries()

        # Extraemos las búsquedas en aumento
        rising = related[kw]['rising']

        if rising is not None:
            print(f"🚨 Alerta de Desinformación asociada a la idea: '{kw.upper()}'")
            # Mostramos el top 3 de forma descriptiva
            for index, row in rising.head(3).iterrows():
                query = row['query']
                crecimiento = row['value']
                print(f"   ❌ La gente está buscando: '{query}'")
                print(f"   📈 Esta búsqueda explotó un {crecimiento}% recientemente.\n")

        # Pausa de 1 segundo para que Google no nos bloquee por hacer muchas consultas
        time.sleep(1)

    except Exception as e:
        print(f"Error con {kw}: {e}")

from pytrends.request import TrendReq
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time

# 1. Configuración de Pytrends y Diseño
sns.set_theme(style="whitegrid")
pytrends = TrendReq(hl='en-US', tz=360)

# 2. Tu lista ampliada de palabras clave del "Nuevo Negacionismo"
keywords = ["climate hoax", "climate scam", "global warming fake", "glaciers growing", "climate change lie"]

# Lista para guardar todos los descubrimientos
todas_las_tendencias = []

print("Extrayendo datos masivos de Google Trends... (Esto tomará unos 10 segundos)")

# 3. Iterar por cada palabra clave y extraer las búsquedas relacionadas
for kw in keywords:
    try:
        pytrends.build_payload(kw_list=[kw], timeframe='today 12-m')
        related = pytrends.related_queries()

        # Si la API nos devuelve búsquedas en aumento ('rising') para esta palabra:
        if related and kw in related and related[kw]['rising'] is not None:
            df_rising = related[kw]['rising'].copy()
            df_rising['origen'] = kw # Guardamos de dónde vino la búsqueda
            todas_las_tendencias.append(df_rising)
            print(f"✅ ¡Se encontraron tendencias ocultas para: '{kw}'!")

        # Pausa vital para que Google no nos bloquee en el Hackathon
        time.sleep(1.5)
    except Exception as e:
        print(f"⚠️ Sin datos para {kw} o error de conexión.")

# 4. Procesar y Graficar si encontramos datos
if todas_las_tendencias:
    # Unir todos los dataframes en uno solo
    df_final = pd.concat(todas_las_tendencias)

    # Ordenar por crecimiento y quedarnos con el Top 10 más explosivo
    top_10 = df_final.sort_values(by='value', ascending=False).head(10)

    # Invertir el orden para que el más grande salga hasta arriba en el gráfico
    top_10 = top_10.iloc[::-1]

    # Crear el Gráfico de Barras Horizontal
    plt.figure(figsize=(11, 6), dpi=150)
    ax = sns.barplot(x='value', y='query', data=top_10, color='#d62728', orient='h')

    # Títulos y Etiquetas Profesionales
    plt.title('El "Nuevo Negacionismo" en Acción: Narrativas en Crecimiento', fontsize=16, fontweight='bold', pad=20)
    plt.xlabel('Crecimiento Porcentual en Google Trends (Últimos 12 meses)', fontsize=12)
    plt.ylabel('Búsquedas Exactas del Público', fontsize=12)

    # Añadir los porcentajes encima de cada barra
    for p in ax.patches:
        width = p.get_width()
        # Formateamos el número con comas y el símbolo de porcentaje
        ax.annotate(f'+{int(width):,}%',
                    (width, p.get_y() + p.get_height() / 2.),
                    ha='left', va='center',
                    xytext=(8, 0), textcoords='offset points',
                    fontsize=11, fontweight='bold', color='black')

    # Limpieza visual
    sns.despine(left=True, bottom=True)

    # Expandimos un poco el eje X para que el texto del porcentaje no se corte
    max_val = top_10['value'].max()
    plt.xlim(0, max_val + (max_val * 0.2))

    plt.tight_layout()
    plt.savefig('grafico_barras_conspiraciones.png')
    print("\n🚀 ¡Gráfico de impacto generado con éxito: 'grafico_barras_conspiraciones.png'!")
    plt.show()

else:
    print("\nNo se encontraron tendencias en aumento hoy para estas palabras.")